.github/workflows/labext-ci.yml, tox.ini
Setup of a CI for LabExT to run tests automatically for each push. This can also be used for linters later.
Use of a Github action, which is triggered for every push. In addition, Tox is used, which is a wrapper for pytest. Tox first generates a package from the code and then calls pytest to run all tests (files with * _test.py).
Further information can be found at: https://github.com/tox-dev/tox
This PR does not introduce any new functions in LabExT, but only sets up GitHub for CI. Nevertheless, all runs will fail because pytest has not yet found any tests and so exits with status code 1.
=> Github workflow for LabExT

LabExT/Movement/Stage.py, LabExT/Movement/Stage3DSmarAct.py, LabExT/Tests/Movement/Stage3DSmarAct/Base_test.py, LabExT/Tests/Movement/Stage3DSmarAct/Channel_test.py, LabExT/Tests/Movement/Stage3DSmarAct/SmarActTestCase.py
This PR introduces a new interface for all stages in LabExT, a stage implementation for SmarAct and unit tests.
The idea is to have a unified interface for all stages in LabExT to make future devices easier to implement and have more consistency.
Important: To keep the changes in this PR small, the interface is the same as in [PiezoStage](https://github.com/LabExT/LabExT/blob/main/LabExT/Movement/PiezoStage.py), so existing code will continue to work. The interface can be revised later.
Mocks are used to enable testing. I propose to simulate the PythonWrapper module for SmarAct and assume that it works without errors. The written tests verify that LabExT calls the functions correctly and handles all return values correctly.
- [`Stage`](https://github.com/LabExT/LabExT/pull/11/files#diff-51 …
=> [Movement] Refactor: Introduce Stage interface and SmarAct implementation

LabExT/Movement/Stage3DSmarAct.py, LabExT/Tests/Movement/Stage3DSmarAct/Channel_test.py
**Don't merge before https://github.com/LabExT/LabExT/pull/11**
Add a "kill-switch" for stages.
By invoking the driver method `SA_Stop_S`, all stage movement will be stopped. We can later introduce a keyboard shortcut that automatically stops all movements in case the user detects dangerous movements of the stages.
This will not break anything.
=> [Movement] Stop method for SmarAct stages

LabExT/Movement/Stage.py, LabExT/Movement/Stage3DSmarAct.py, LabExT/Tests/Movement/Stage3DSmarAct/Base_test.py, LabExT/Tests/Movement/Stage3DSmarAct/Channel_test.py, LabExT/Tests/Movement/Stage3DSmarAct/SmarActTestCase.py
**Don't merge before https://github.com/LabExT/LabExT/pull/11**
Add a classmethod to Stage3DSmarAct for finding all SmarAct stages.
By invoking the driver method `SA_FindSystems`, we should be able to find all usb-connected stages.
This will not break anything, since we aren't using the method yet.
=> [Movement] Find SmarAct systems

LabExT/View/Controls/PlotControl.py, LabExT/View/LiveViewer/LiveViewerController.py, LabExT/View/LiveViewer/LiveViewerModel.py, LabExT/View/LiveViewer/LiveViewerView.py
Add live-viewer feature: limit y-axis scaling to minimum.
When using the live viewer, the y-axis currently is scaled to always show the total y-axis range + 20%. This could mean that the y-axis spans about 0.2 dB during optical coupling, which is too small to make sense. Ideally, we want to lower-limit to 1 to 2 dB y axis range.
Adding the property `min_y_axis_span` to PlotControl plus the scale limiting in `__handle_scaling__`. Further, the LiveViewer controller sets the attribute on clicking the apply settings button.
No compatibility issues expected, its just a small added feature to PlotControl which is disabled by default.
=> Feature: Limit y-axis scaling in live viewer

LabExT/Movement/Stage.py, LabExT/Movement/Stage3DSmarAct.py, LabExT/Tests/Movement/Stage3DSmarAct/Base_test.py, LabExT/Tests/Movement/Stage3DSmarAct/SmarActTestCase.py, LabExT/Tests/Movement/Stage_test.py
Raise Runtime error when trying to invoke a stage method which requires an active stage connection and loaded drivers.
Introducing a decorator for functions which needs stage driver and stage connection. A runtime error is triggered if one of these conditions is not met.
I also added tests for the decorator.
This a follow-up PR of #17
=> [Movement] Decorator for safe access to the stage methods

LabExT/Instruments/LaserMainframeKeysight.py, LabExT/Instruments/PowerMeterGenericKeysight.py
Apparently, on older mainframe (816xB) firmwares a -261:StatUnitCalculationError will appear on very low optical input powers. For the explanation, see this excerpt of the 8164B Programming Guide: 
In this PR, we simply ignore the error, as its annoying and interrupts live viewing and measurements. We can savely ignore it, as too low optical powers get recorded as NaN anyhow. (Except on the N77xx models, which report a -200dBm value for too low powers.)
=> bugfix: ignore Keysight mainframe dB calculation error 

.readthedocs.yaml
RTD should be configured correctly now.
=> Adding .readthedocs.yaml config file for RTD as building now requires Python 3.8

LabExT/Tests/Utils.py, LabExT/Tests/View/Controls/Wizard_test.py, LabExT/View/Controls/Wizard.py, tox.ini
This pull request adds a widget to easily create wizard windows in LabExT. Detailed documentation on how to use it can be found below. Tests have been added to test functionality (e.g. button clicks) rather than appearance. 
**The code does not break any existing code. It simply adds code that is not already in use.**
Create a class that inherits from `Wizard`. Call the `Wizard` constructor to set the basic settings. 
```python
from LabExT.View.Controls.Wizard import Wizard
class MyWizard(Wizard):
def __init__(self, parent):
super().__init__(
parent, # required
width=800, # Default: 640
height=600, # Default: 480
with_sidebar=True, # Default: True
with_error=True, # Default: True
on_cancel=self._cancel, # not required
on_finish=self._save, # not required
next_button_label="Next Step" # …
```
=> [View] Wizard Widget

LabExT/Tests/Utils.py, LabExT/Tests/View/Controls/DriverPathDialog_test.py, LabExT/View/Controls/DriverPathDialog.py
**Needs #33 merged before!**
This pull request adds a widget to store driver paths in a general way. It has the same functionality as StageDriverSettingsDialog, except that DriverPathDialog is built in a general way.  Tests have been added to test functionality (e.g. button clicks) rather than appearance. 
**The code does not break any existing code. It simply adds code that is not already in use.**
```python
def load_driver(cls, parent=None) -> bool:
"""
Loads driver for SmarAct by open a dialog to specifiy the driver path.
"""
driver_path_dialog = DriverPathDialog(
parent,
settings_file_path="mcsc_module_path.txt",
title="Stage Driver Settings",
label="SmarAct MCSControl driver module path",
hint="Specify the directory where the module MCSControl_PythonWrapper is found.\nThis is …
```
=> [View] Dialog for Driver Path

LabExT/Tests/runtests.py
Use pytest return code to tell tox if the run has passed or not.
=> Fix: Use sys.exit after pytest

LabExT/View/ProgressBar/ProgressBar.py
The indeterminate loading bar was not centered on the screen. This was due to us reading the width of the loading bar window before the widgets were actually created. In this PR, code is introduced to let tkinter create the widgets and only after we set the location and size of the loading bar window.
=> Bugfix: loading-bar was not in center of screen

LabExT/ExperimentManager.py, LabExT/View/Controls/ControlPanel.py, LabExT/View/MainWindow/MainWindowController.py, LabExT/View/MainWindow/MainWindowView.py
An often wished for feature: The live-viewer (and the search-for-peak window) should be available via shortcuts and prominently placed buttons.
This PR introduces the buttons in the Main Window to quickly open live-viewer and search-for-peak. The live-viewer is now available by pressing Ctrl+L, the SfP window by Ctrl+S.
This PR also contains two "beautifying" additions:
* The horizontal control buttons are now properly padded.
* The Label-Frames in the MainWindow have more telling titles and are ordered according to their usage in a classical measurement scenario.
This PR also contains the following refactoring:
* Registering the main-window's keyboard shortcuts is now done in `MainWindowController` instead of in the very unfitting `ExperimentManager`.
=> Add quickaccess for coupling tools

LabExT/Movement/Calibration.py, LabExT/Movement/Transformations.py, LabExT/Tests/Movement/Calibration_test.py, LabExT/Tests/Movement/Transformations_test.py, LabExT/Tests/Utils.py, LabExT/Tests/View/CoordinatePairingsWindow_test.py, LabExT/Tests/View/MovementWizard_test.py, LabExT/Tests/View/StageCalibration_test.py, LabExT/View/Controls/CoordinateWidget.py, LabExT/View/Movement/CoordinatePairingsWindow.py, LabExT/View/Movement/StagePositionWidget.py, LabExT/View/StageCalibration/StageCalibrationController.py, LabExT/View/StageCalibration/StageCalibrationView.py
This PR adds another step to the calibration of the stages. For each stage a coordinate pair of chip and stage coordinate is defined, which can be used to calculate a translation. Together with the axis-calibration it is possible to move approximate absolute in chip-coordinates.
- `Transformation`: Is an abstract base class, so this cannot be initialised directly and provides an interface for all transformations in LabExT. This requires that the functions `chip_to_stage`, `stage_to_chip` and `is_valid` are defined.
- `CoordinatePairing`: `NamedTuple`. Quadruple of calibration (aka stage), stage coordinate (list), device and chip coordinate.
- `SinglePointFixation` is a transformation. It stores a chip and stage cooridnate and calculates an offset from these. This is added to the …
=> [Movement] (3/5): Single Point für safe absolute (approx) movement

LabExT/Experiments/StandardExperiment.py, LabExT/View/MainWindow/MainWindowModel.py, LabExT/View/MainWindow/MainWindowView.py
Add an optional waiting time
Below the manual mode checkbox in the experiment control section in the main GUI there is now a text box entry which allows to enter the wait time. When running the experiment and manual mode is disabled, the experiment runner will pause for the set amount of seconds after every successfully completed ToDo.
* The wait time can only be changed if manual mode is disabled. If a negative number is entered, the wait time is set to 0.
* Also removed the "Finish" button from the main window, as it was without functionality anyway.
No compatibility issues expected.
=> Add an optional wait time between measurements

LabExT/View/MainWindow/MainWindowController.py
This is just a quick bugfix for the currently available quick access buttons for the SfP and live viewer.
=> bugfix: quick access buttons now work

.github/workflows/labext-ci.yml, LabExT/ExperimentManager.py, LabExT/Experiments/StandardExperiment.py, LabExT/Tests/Utils.py, LabExT/Tests/View/Controls/DriverPathDialog_test.py, LabExT/Tests/View/MainWindow_test.py, LabExT/View/MainWindow/MainWindowController.py, LabExT/View/MainWindow/MainWindowModel.py, LabExT/View/TooltipMenu.py, pytest.ini, requirements.txt, requirements_testing.txt
This PR tries to add a full click-through unittest of the basic InsertionLossSweep measurement within the tkinter GUI.
=> Adding a full click-through unittest of running an InsertionLoss measurement with simulated instruments

LabExT/Movement/Calibration.py, LabExT/Movement/config.py, LabExT/Tests/Movement/Calibration_test.py
Adds a decorator. This decorator executes the decorated method only if the state of the calibration is at least the defined one. Different states can be defined for both coordinate systems (chip, stage). A total order among the states was defined:
```
UNINITIALIZED  < CONNECTED  < COORDINATE_SYSTEM_FIXED < SINGLE_POINT_FIXED < FULLY_CALIBRATED
```
Furthermore, a property `coordinate_system` was added to the calibration. This decides in which system later methods are to be executed. Context managers were added to facilitate handling.
=> Movement Calibration [2/7] Coordinate system management

LabExT/Movement/Calibration.py, LabExT/Tests/Movement/Calibration_test.py
Adds a method to move the stage absolutely. If it is to be moved in stage coordinates, no change is made. If it is to be moved in chip coordinates, a valid transformation (kabsch or single point) must be defined to convert the chip coordinate to a stage coordinate.
=> Movement Calibration [6/7] Move Absolute

LabExT/Movement/Calibration.py, LabExT/Tests/Movement/Calibration_test.py
Adds a method to move the stage relatively. If it is to be moved in stage coordinates, no change is made. If it is to be moved in chip coordinates, a valid axis rotation must be defined to convert the chip coordinate to a stage coordinate.
=> Movement Calibration [5/7] Stage relative movement

LabExT/Movement/Calibration.py, LabExT/Tests/Movement/Calibration_test.py
Adds a method to read out the position of the stage in stage coordinates (no change) or in chip coordinates. To read it in chip coordinates, you need at least a single point offset transformation or a Kabsch rotation, the later being preferred.
=> Movement Calibration [4/7] Position of Stage

LabExT/Movement/Calibration.py, LabExT/Tests/Movement/Calibration_test.py
Adds methods to connect and disconnect from the stage and to change axis rotation, single point offset or full calibration. 
These methods call the corresponding transformations. After each update, a method is called to determine the new state of the calibration. This works as follows:
1. checks whether the stage responds. If so, the status is at least `CONNECTED`.
2. checks whether the axis rotation is valid. If yes, the status is at least `COORDINATE SYSTEM FIXED`.
3. checks whether the single point fixation is valid. If yes, the status is at least `SINGLE POINT FIXED`.
4. checks whether the full calibration is valid. If yes, the status is `FULLY CALIBRATED`.
=> Movement Calibration [3/7] Update the calibration and state

.github/workflows/labext-ci.yml, LabExT/Tests/View/Controls/DriverPathDialog_test.py, LabExT/Tests/View/Controls/Wizard_test.py, LabExT/Tests/View/MainWindow_test.py, requirements.txt, requirements_testing.txt, tox.ini
Introduce running the CI also on Windows OS.
Simply add the OS to the matrix of OSxVersions of the GitHub runner yaml config file.
No compatility issues expected. I had to rewrite some tests for these to make file paths OS agnostic.
=> Adding CI testing to run under Windows runners, too

LabExT/Tests/View/CoordinatePairingsWindow_test.py
Add flaky decorator to `CoordinatePairingsWindowTest`
=> Fix: CoordinateWindowTest

LabExT/View/ProgressBar/ProgressBar.py
There is a bug in TKinter 8.6 (shipped with Python 3.7 - 3.9) that the `Toplevel.overrideredirect(True)` results in an error. This is a TKinter bug, see https://github.com/PySimpleGUI/PySimpleGUI/issues/3048 so we just implement a simple workaround.
Fixes #79
=> Workaround: MacOS not starting due to TKinter bug

.github/workflows/test_documentation_compilation.yml, docs/reference_InstrumentAPI.md
So far, we did not notice if docs compilation fails before we actually merged into main branch. This CI fixes this: CI would fail if mkdocs cannot compile the documentation.
Improve visibility in documentation generation
Adding a CI workflow which compiles the documentation using mkdocs. If mkdocs detects any errors in building the docs, the CI will fail and one can see it in a pull request.
Just adding a single CI job, no compatibility issues expected.
=> Adding test-compilation of docs to CI

LabExT/Movement/Calibration.py, LabExT/Movement/MoverNew.py, LabExT/Movement/PathPlanning.py, LabExT/Movement/Stage.py, LabExT/Movement/Stages/DummyStage.py, LabExT/Movement/Stages/Stage3DSmarAct.py, LabExT/View/Movement/CoordinatePairingsWindow.py, LabExT/View/Movement/MovementWizard.py
Adds a base class to define stage polygons in LabExT for path planning.
The first polygon is for a DC Probe, which is a rectangular polygon defined by fiber length, fiber radius and safety distance.
=> [Movement] Path Planning: Stage Polygons

LabExT/Movement/Calibration.py, LabExT/Movement/Transformations.py, LabExT/Tests/Movement/Calibration_test.py
This pull request adds two methods to the calibrations to export calibrations and load them again.
`dump` will export a calibration to a dict. `load` will take that dict together with a stage and mover to create a calibration object again.
=> [Movement]: Dump and load calibrations

LabExT/Movement/Calibration.py, LabExT/Movement/Transformations.py, LabExT/Tests/Movement/Calibration_test.py, LabExT/Tests/Movement/Transformations_test.py
Added methods for dumping and loading transformation.
Each transformation (Axes Rotation, Single Point Offset and Kabsch Rotation) have a method to dump (export the transformation into some storable format) and to load (create transformation out of the stored format)
Tests have been added to verify the behaviour.
=> [Movement]: Dump and load transformations

LabExT/Movement/Calibration.py, LabExT/Movement/MoverNew.py, LabExT/Movement/Transformations.py, LabExT/Movement/config.py, LabExT/Tests/Movement/Calibration_test.py, LabExT/Tests/Movement/MoverNew_test.py, LabExT/Tests/Movement/Transformations_test.py, LabExT/View/MainWindow/MainWindowView.py, LabExT/View/MenuListener.py, LabExT/View/Movement/MoveStagesDeviceWindow.py, LabExT/View/Movement/MoveStagesRelativeWindow.py, LabExT/View/Movement/__init__.py
Implements move relative in new Mover.
Relative movements are performed without collision avoidance. When multiple stages are requested to move, they move clockwise unless otherwise requested.
Tests for this behavior have been added.
=> [Movement]: Move relative method

LabExT/Movement/Calibration.py, LabExT/Movement/MoverNew.py, LabExT/Movement/PathPlanning.py, LabExT/Movement/config.py, LabExT/Tests/Movement/Calibration_test.py, LabExT/Tests/Movement/MoverNew_test.py, LabExT/View/Controls/CoordinateWidget.py, LabExT/View/Movement/CoordinatePairingsWindow.py
Removed some constraints on setting the coordinate system for calibrations.
Simplify coordinate system control in calibrations.
Recall: Each `Calibration` (`Calibration` is an abstraction of one `Stage` which contains all data to allow the stage to move in any coordinate system, e.g. in Chip or Stage system) stores a value `coordinate_system` which specifies the system in which all operations on this stage should be performed. The following options are available: 
```python
class CoordinateSystem(BaseEnum):
UNKNOWN = 0
STAGE = 1
CHIP = 2
```
The default is `CoordinateSystem.UNKNOWN`. If this is the case, no operation (e.g `move_relative`, `get_position`) can be performed, since the system is not clear.
To change this, one needs to use the `set_coordinate_system` method on the calibration …
=> [Movement] Simplify and stabilise coordinate control

LabExT/Movement/Calibration.py, LabExT/Movement/MoverNew.py, LabExT/Movement/PathPlanning.py, LabExT/Movement/Stages/Stage3DSmarAct.py, LabExT/Movement/config.py, LabExT/SearchForPeak/PeakSearcher.py, LabExT/Tests/Movement/Calibration_test.py, LabExT/Tests/Movement/MoverNew_test.py, LabExT/Tests/Movement/Stage3DSmarAct_test.py, LabExT/View/Controls/CoordinateWidget.py, LabExT/View/Movement/CoordinatePairingsWindow.py
Makes `SearchForPeak` workable with new Mover without changing much in the general structure of the algorithm. When we redesign SfP, we can make this prettier. All fixes discovered during testing in the lab are included.
=> [Movement]: Make SfP applicable for new mover

LabExT/Tests/View/CoordinatePairingsWindow_test.py, LabExT/View/MenuListener.py, LabExT/View/Movement/CoordinatePairingsWindow.py, LabExT/View/Movement/MovementWizard.py
This PR adds two optional shortcuts in the Coordinate Pairing Window for Search for Peak and Live Viewer. This makes pairing creation easier.
In the future, when we define the new interface for SfP, we can directly set the required stages to perform the SfP Algorithm.
=> [Movement v1] SfP and Live Viewer shortcuts

LabExT/Movement/MoverNew.py, LabExT/Tests/View/CoordinatePairingsWindow_test.py, LabExT/View/MenuListener.py, LabExT/View/Movement/CoordinatePairingsWindow.py, LabExT/View/Movement/MovementWizard.py
Small cosmetic fix: If only one stage was connected, checkboxes for using input and output calibration were still displayed in the coordinate pairing step. These are now only displayed if such a calibration exists.
=> [Movement v1] Fix stage checkboxes for pairing for single stages

LabExT/Movement/MoverNew.py, LabExT/Tests/Movement/MoverNew_test.py, LabExT/Tests/View/CoordinatePairingsWindow_test.py, LabExT/View/MenuListener.py, LabExT/View/Movement/CoordinatePairingsWindow.py, LabExT/View/Movement/LoadStoredCalibrationWindow.py, LabExT/View/Movement/MovementWizard.py
Restores Mover settings (lift, acceleration, speed) after LabExT restart.
After initialisation of the mover, it is checked whether a Mover Settings file exists. If so, the values are loaded from the file and saved in the internal mover state (`_speed_xy`, `_acceleration_xy`, `_z_lift`, `_speed_z`). If a new stage is registered in the mover as a calibration, the internal state is automatically set as a setting after connecting to the stage. This guarantees that every stage known to the Mover has the same settings.
If the file is not found, the constant default values are used as before.
=> [Movement v1] Restore Mover settings from file

LabExT/Movement/MoverNew.py, LabExT/Movement/Transformations.py, LabExT/Tests/Movement/MoverNew_test.py, LabExT/Tests/Movement/Transformations_test.py, LabExT/Tests/View/CoordinatePairingsWindow_test.py, LabExT/View/MenuListener.py, LabExT/View/Movement/CoordinatePairingsWindow.py, LabExT/View/Movement/LoadStoredCalibrationWindow.py, LabExT/View/Movement/MovementWizard.py
Fixes bug of resetting axes rotation after declining calibration loading.
Before we created a new `AxesRotation` after declining which was not updated during the calibration process such that Kabsch did not correct the unit vectors during calibration.
=> [Movement v1] Fix bug of reset axes rotation after declining calibration loading

LabExT/Movement/Calibration.py, LabExT/Movement/MoverNew.py, LabExT/Movement/Transformations.py, LabExT/Tests/Movement/MoverNew_test.py, LabExT/Tests/Movement/Transformations_test.py, LabExT/Tests/View/CoordinatePairingsWindow_test.py, LabExT/View/MenuListener.py, LabExT/View/Movement/CoordinatePairingsWindow.py, LabExT/View/Movement/LoadStoredCalibrationWindow.py, LabExT/View/Movement/MovementWizard.py
This PR introduces two new methods at the calibration level: `lift_stage_relative` and `lower_stage_relative`. These allow the stage relative to be lifted and lowered. The chip offset `ChipCoordinate(x=0, y=0, z=z_lift)` or `ChipCoordinate(x=0, y=0, z=-z_lift)` is aimed at, which allows (after coordinate-axis calibration, i.e. State: `COORDINATE_SYSTEM_FIXED`) to raise or lower the stages relative. The state `is_lifted` is also used here to prevent double lowering/lifting.
In addition to these methods, there are the general methods `lift_stage` and `lower_stage`. This performs the relative or absolute lift/lowering depending on the calibration state.
For `FULLY_CALIBRATED`: Lift/Lower Stage absolute. The skewness of the chip is known (approximately).
For `SINGLE_POINT_FIXED` and …
=> [Movement v1] Lift/Lower relative and absolute

LabExT/Movement/Calibration.py, LabExT/Movement/MoverNew.py, LabExT/Movement/PathPlanning.py, LabExT/Movement/Transformations.py, LabExT/Tests/Movement/MoverNew_test.py, LabExT/Tests/Movement/Transformations_test.py, LabExT/Tests/View/CoordinatePairingsWindow_test.py, LabExT/View/MenuListener.py, LabExT/View/Movement/CoordinatePairingsWindow.py, LabExT/View/Movement/LoadStoredCalibrationWindow.py, LabExT/View/Movement/MovementWizard.py
Lift and Lower is now the responsibility of the calibration. Path finding keeps the z-coordinate constant during movement.
Changed the lift and lowering of the stages. Added methods to lift and lower stages at the calibration level (Recall: `Calibration` is an abstraction of a stage that holds all the information to move stages in chip or stage coordinate system, e.g., Kabsch rotation). Each calibration stores a bool `_is_lifted`, indicating whether the stage is currently lifted. This prevents double lifting or lowering.
A `z-lift` value is passed. The stage moves in chip coordinates to `[x,y,z-lift],` where `x` and `y` are the current `x` and `y` values.
The stage moves (independent of the previously passed `z-lift` value) to the position `[x,y,0]`, where `x` and `y` are the stage's …
=> [Movement v1] Lifting and Lowering of Stages

LabExT/Movement/Calibration.py, LabExT/View/Movement/LoadStoredCalibrationWindow.py
As discussed with @delmedico and @boris-vukovic in the lab, another check makes sense to see if the calibrations to be restored were made with the same stages. If this is not the case, a warning is issued and we require explicit consent from the user.
=> [Movement v1] Safety: Check for stage identifier before restore

LabExT/Movement/Calibration.py, LabExT/Movement/MoverNew.py, LabExT/Movement/Stage.py, LabExT/Movement/Stages/DummyStage.py, LabExT/Movement/Stages/Stage3DSmarAct.py, LabExT/View/Movement/LoadStoredCalibrationWindow.py, LabExT/View/Movement/MovementWizard.py
Adds identifiers for stages that remain the same after a LabExT restart. These are needed in #112 to distinguish settings for stages.
=> [Movement v1] Introduce identifier for stages

LabExT/View/Movement/MovementWizard.py
This PR adds a button in the calibration process that allows to delete all saved pairings. A warning is given beforehand.
=> [Movement v2] Reset coordinate pairings

LabExT/View/Movement/MovementWizard.py, LabExT/Wafer/Device.py
Fixes the error that the string representation of a device in the Coordinate Pairing Table is too long. This has now been replaced by a shorter string.
=> [Movement v2] Fix device description overflow in coordinate pairing table

LabExT/Movement/Transformations.py, LabExT/View/Movement/MovementWizard.py
Adds the angle between the chip plane and the XY plane in the calibration window. The angle is given in radians, degrees and percentages.
=> [Movement v2] Plane angle

LabExT/Movement/Calibration.py, LabExT/Movement/MoverNew.py, LabExT/Movement/PathPlanning.py
Introduction of an interface for path planning in the Mover.
- `set_stage_target`: Given a calibration instance and a chip coordinate as a target, we define which calibration has which target.
- `trajectory`: Generator that iteratively creates a waypoint command. Why generator: Generators are more general than simple lists, and allow the calculation of waypoints that are not yet known at the time of the call. The `CollisionAvoidancePlanning` with potential field (previously `PathPlanning`) uses this. 
Furthermore, `PathPlanning` has been renamed `CollisionAvoidancePlanning`. The algorithm is the same.
The `Waypoint` NamedTuple defines the calibration, coordinate, and `wait_for_stopping` for a calculated waypoint. Not really a big change than before, except that we get more unity within …
=> [Movement v2] Path Planning Abstraction

LabExT/Movement/Stage.py, LabExT/Movement/Stages/DummyStage.py, LabExT/Movement/Stages/Stage3DSmarAct.py, LabExT/Tests/Movement/PiezoStage_test.py, LabExT/Tests/Movement/Stage3DSmarAct_test.py
Lifting, lowering and axis invert is now the responsibility of the a Calibration. This PR removes the legacy support to lift, lower stages on Stage level.
=> Remove lifting and lowering on stage level

LabExT/View/MainWindow/MainWindowController.py, LabExT/View/Movement/MovementWizard.py
Currently we do not allow to open the Stage Calibration Wizard if no chip has been imported.
In particular, this does not allow you to adjust the axes, which does not require a chip.
The changes introduce an extra frame in the coordinate pairing step that shows the currently imported chip, which gives more information. If the chip is missing, we provide a shortcut to import a chip. The wizard will then be reloaded. If no chip has been imported, no coordinate pairings can be created. The buttons are therefore deactivated.
Without imported chip:
With imported chip:
=> Update workflow for stage calibration when Chip is not imported

LabExT/Movement/Calibration.py, LabExT/Movement/PathPlanning.py, LabExT/Tests/Movement/Calibration_test.py, LabExT/Tests/Movement/PathPlanning_test.py
This PR allows to save and restore polygons on the hard disk. Polygons are now saved in the calibration data.
Why do I save the orientation in the polygon: This is already a design change for a later PR. The orientation is not used anywhere except for the stage polygons. Therefore, I think they are better off as parameters for polygons than as parameters in the calibrations. I will discuss this in a later PR.
=> Allow to store and restore stage polygons

LabExT/ExperimentManager.py, LabExT/Instruments/LaserMainframeKeysight.py, LabExT/Instruments/PowerMeterN7744A.py
Small improvements regarding the supplied Keysight TLS and OPM classes.
Actually increases compatibility! N7744A class is actually compatible with all N774x keysight multichannel OPMs. The LaserMainframeKeysight class is compatible with all 8164 and 7776/7778 lasers.
=> Quality-of-life improvements for Keysight Laser / OPM

LabExT/ExperimentManager.py, LabExT/Movement/MoverNew.py, LabExT/Tests/Movement/MoverNew_test.py, LabExT/View/MainWindow/MainWindowController.py, LabExT/View/MenuListener.py, LabExT/View/Movement/LoadStoredCalibrationWindow.py
Automatically fills in the stage with which the calibration was created. This makes the restoring process of calibrations easier and safer. In addition, the code has been simplified.
=> Prefill calibrations when restoring and make window to restore simpler

LabExT/ExperimentManager.py, LabExT/Experiments/StandardExperiment.py, LabExT/Instruments/InstrumentAPI/InstrumentAPI.py, LabExT/Movement/MoverNew.py, LabExT/PluginLoader.py, LabExT/SearchForPeak/PeakSearcher.py, LabExT/View/AddonSettingsDialog.py, LabExT/View/Movement/MovementWizard.py
This pull request refactors code for loading plugins into LabExT core and addons. The method `import_plugins_from_paths` allows classes of a base class to import multiple paths and collect statistics of the import. This can be used in Mover, Instruments and Measurements. Redundant code was replaced. The class `PluginAPI` is a simple interface and factory to access and load the loaded plugins in a uniform way.
In the Mover it is now possible to load StagePolygon and Stages via the API. Later SfP and PathPlanner will be added.
=> (1/8) Extend Addons for Mover and refactor plugin loading

LabExT/Measurements/MeasAPI/Measparam.py, LabExT/Movement/Calibration.py, LabExT/Movement/MoverNew.py, LabExT/Movement/PathPlanning.py, LabExT/Movement/config.py, LabExT/PluginLoader.py, LabExT/Tests/Movement/Calibration_test.py, LabExT/Tests/Movement/PathPlanning_test.py, LabExT/View/Movement/MovementWizard.py
This pull request adds the orientation property as a StagePolygon property. Furthermore, StagePolygon is automatically saved and loaded on disk for class names by MoverAPI.
=> (2/8) Add orientation to Single Mode Fiber stage polygon

LabExT/Movement/Calibration.py, LabExT/Movement/Stage.py, LabExT/Movement/Stages/Stage3DSmarAct.py, LabExT/Tests/Movement/Calibration_test.py
Add methods to save stage properties to disk and load them again. Use the new MoverAPI to load available stage classes/implementations.
=> (7/8) Add load and dump for Stages

LabExT/Movement/Calibration.py, LabExT/Movement/MoverNew.py, LabExT/Movement/Stage.py, LabExT/Movement/Stages/Stage3DSmarAct.py, LabExT/Tests/Movement/Calibration_test.py, LabExT/Tests/Movement/MoverNew_test.py, LabExT/Tests/View/CoordinatePairingsWindow_test.py, LabExT/Tests/View/StageRegistrationWindow_test.py, LabExT/View/Controls/StageTable.py, LabExT/View/MainWindow/MainWindowView.py, LabExT/View/Movement/CoordinatePairingsWindow.py, LabExT/View/Movement/MovementWizard.py, LabExT/View/Movement/StageRegistrationWindow.py
**This is the most curial part of the rewrite. Happy to discuss this remotely.**
This pull request removes the Orientation Property from Calibration and Mover Level. This is now part of the StagePolygon.
New:
- Mover now stores a normal list of calibrations (theoretically now any number).
- Mover manages a mapping from port (currently: input and output) to a calibration. These calibrations are used in Move-to-Device.
- Calibrations have a property `is_automatic_movement_enabled`. This is true if the calibrations has a port AND a stage polygon assigned. This calibration can be used for Move-to-Device.
The mover has been simplified considerably. All calibrations can be registered with Mover as long as they do not use a stage or port twice.
=> (3/8) Remove Orientation Property from Mover

LabExT/View/MainWindow/MainWindowModel.py
This is a super small change. Basically it allows the user to change the name of the chip in the main window after a measurement is executed. Meaning, one can perform two measurements with different chip names in the same LabExT session without closing and reopening the GUI. 
Only if a chip is imported, the chip name cannot be changed anymore. This holds also true if a chip is loaded from the last session.
=> Allow changes to chip name if no chip imported

LabExT/Logs/MaxLevelFilter.py, LabExT/Main.py
This feature allows the user to specify what should be logged to the console. The channels used for logging are now seperated: debug/info -> stdout, warning/error -> stderr.
=> Console logging

LabExT/Experiments/StandardExperiment.py, LabExT/Measurements/MeasAPI/Measurement.py, LabExT/Tests/View/MainWindow_test.py, LabExT/View/Controls/AdhocDeviceFrame.py, LabExT/View/Controls/InstrumentSelector.py, LabExT/View/Controls/KeyboardShortcutButtonPress.py, LabExT/View/Controls/ParameterTable.py, LabExT/View/EditMeasurementWizard/EditMeasurementWizardController.py, LabExT/View/EditMeasurementWizard/EditMeasurementWizardModel.py, LabExT/View/EditMeasurementWizard/EditMeasurementWizardView.py, LabExT/View/EditMeasurementWizard/WizardEntry/Base.py, LabExT/View/EditMeasurementWizard/WizardEntry/DeviceSelect.py, LabExT/View/EditMeasurementWizard/WizardEntry/Factory.py, LabExT/View/EditMeasurementWizard/WizardEntry/FinishedError.py, LabExT/View/EditMeasurementWizard/WizardEntry/InstrumentSelect.py, LabExT/View/EditMeasurementWizard/WizardEntry/MeasurementSelect.py, LabExT/View/EditMeasurementWizard/WizardEntry/ParamSelect.py, LabExT/View/EditMeasurementWizard/WizardEntry/SaveButtons.py
This pull request refactors the code for the edit measurement wizard. Instead of using hardcoded functions for each stage/entry in the wizard, we now have an abstract base class for the wizard entries which can be inherited. It provides most of the functionality. The subclasses only need to specify their content and what happens on serializing and deserializing.
Each of the 8 commits integrates one entry in the wizard, except for the first two, which create the new method interface and adapt the `EditMeasurementWizardController` to it.
The methods for the old way of creating gui entries are still in the code and (mostly) unchanged, however, they now log a deprecation warning. They will be removed in the next version of LabExT. Theoretically, no user plugins should ever interact with these …
=> Measurement Wizard Rework

LabExT/Experiments/StandardExperiment.py, LabExT/Instruments/DummyInstrument.py, LabExT/Measurements/DummyMeas.py, LabExT/Tests/View/ExperimentWizard_test.py, LabExT/View/MainWindow/MainWindowController.py, LabExT/View/MainWindow/MainWindowModel.py, LabExT/View/MainWindow/MainWindowView.py
Remove the live-plot canvas from the LabExT Main Window.
No measurement I have ever seen uses the live-plot feature. Why not use the nice screen real-estate for allowing the user a better view onto the finished measurement's data?
Simple deletion of the relevant parts in MainWindowView plus some references.
Potential compatibility issues: any measurements that made use of the live-viewing feature will need to remove the plotting code to not error-out with an `AttributeError`: The `live_plot_collection` in `StandardExperiment` does not exist anymore.
=> LVI [1/4]: Remove Live Plot from MainWindow

LabExT/Experiments/StandardExperiment.py, LabExT/Instruments/DummyInstrument.py, LabExT/Measurements/DummyMeas.py, LabExT/Tests/View/ExperimentWizard_test.py, LabExT/View/Controls/InstrumentSelector.py, LabExT/View/Controls/ParameterTable.py, LabExT/View/MainWindow/MainWindowController.py, LabExT/View/MainWindow/MainWindowModel.py, LabExT/View/MainWindow/MainWindowView.py, LabExT/View/Movement/MovementWizard.py
Finalize the transition to the new (de-) serialization of parameter and instrument widgets.
The change on how widgets store their state in JSON in files was started in #172. This PR deletes the former function `make_json_able` and switches over to usage of the new functions.
Some old code in `MovementWizard` needed to be updated. The polygon parameter tables used the old function.
No compatibility break expected.
=> LVI [2/4]: Depreciating "json_able" functions in Widgets

LabExT/Experiments/StandardExperiment.py, LabExT/Instruments/DummyInstrument.py, LabExT/Measurements/DummyMeas.py, LabExT/Measurements/MeasAPI/Measurement.py, LabExT/Tests/View/ExperimentWizard_test.py, LabExT/View/Controls/InstrumentSelector.py, LabExT/View/Controls/ParameterTable.py, LabExT/View/LiveViewer/Cards/CardFrame.py, LabExT/View/LiveViewer/Cards/LaserCard.py, LabExT/View/LiveViewer/Cards/PowerMeterCard.py, LabExT/View/LiveViewer/LiveViewerController.py, LabExT/View/LiveViewer/LiveViewerModel.py, LabExT/View/LiveViewer/LiveViewerPlot.py, LabExT/View/LiveViewer/LiveViewerView.py, LabExT/View/MainWindow/MainWindowController.py, LabExT/View/MainWindow/MainWindowModel.py, LabExT/View/MainWindow/MainWindowView.py, LabExT/View/Movement/MovementWizard.py
Improve the Live Viewer: performance wise, some GUI elements and simplified API for cards
* **Performance** Instead of having a call-back based plot (i.e. updates graph as soon as new value was coming in), a polled plotting method is used (via `matplotlib.animation`). This de-couples instrument polling into a separate thread and connects it via a queue to the tk mainloop thread for plotting. To enable better code readability, the required live-plotting functionality was refactored out from `PlotControl` to a highly specific class (`LiveViewerPlot`) which is now used for the LiveViewer plot.
* **GUI/UX**: A bar-plot was added to the right-hand side of the live-viewer plot. It is helpful during coupling to get an immediate impression of the coupling value. The bar plot can be disabled. By …
=> LVI [3/4]: Rewrite of LiveViewer - improve performance for more than one trace, improve GUI, improve LVCard API

LabExT/ExperimentManager.py, LabExT/Experiments/StandardExperiment.py, LabExT/View/Controls/PlotControl.py, LabExT/View/LiveViewer/Cards/CardFrame.py, LabExT/View/LiveViewer/Cards/LaserCard.py, LabExT/View/LiveViewer/Cards/PowerMeterCard.py, LabExT/View/LiveViewer/LiveViewerController.py, LabExT/View/LiveViewer/LiveViewerModel.py, LabExT/View/LiveViewer/LiveViewerPlot.py, LabExT/View/LiveViewer/LiveViewerView.py, pyproject.toml
Some clean-up work after the big live-viewer rewrite is in order
* **PlotControl performance**: small improvements to the `PlotControl` class should enhance performance: 1st the canvas is only redrawn at the end of `plotdata_changed`, not for every plotted line. 2nd extra code takes care of shutting down the polled execution of foreign functions properly when the plot is destroyed. 3rd polling time for executing foreign functions is increased to 50ms, could possibly be increased to 100ms without perceivable difference.
* **Live-viewer not stopped warning**: A messagebox is now shown to the user in case a measurement run is started but the live-viewer is not stopped. This should avert quite some crashes when using the software.
* **Black formatter** The line-length configuration option for …
=> LVI [4/4]: Small Improvements after new LV rewrite: PlotControl performance, Extra-confirmation for run, black config

LabExT/View/LiveViewer/LiveViewerController.py, LabExT/View/LiveViewer/LiveViewerModel.py, LabExT/View/LiveViewer/LiveViewerPlot.py, LabExT/View/LiveViewer/LiveViewerView.py
Directly see insertion loss in live viewer by comparing to a set reference.
There are now three extra buttons in the live viewer for setting/clearing/recalling reference values. These operate on all visible traces in parallel.
The reference values are currently stored/recalled based on the displayed trace label. Using this to associate a reference value might not be optimum, better would be to use the 3-tuple (instrument type, visa address, channel number) as a key for a reference value. But the current implementation gets us to a working referencing system without too much code. Furthermore, it would be great if we could set/reset/recall references per displayed trace and not operate on all traces in parallel.
No compatibility breaks.
note the three buttons w.r.t. referencing on the …
=> Add push-button referencing to live viewer

LabExT/View/LiveViewer/LiveViewerController.py, LabExT/View/LiveViewer/LiveViewerModel.py, LabExT/View/LiveViewer/LiveViewerPlot.py, LabExT/View/LiveViewer/LiveViewerView.py
Improve performance of live viewer by using selective redrawing.
Matplotlib's animation package offers the functionality of blitting - i.e. only redrawing the changed artists. We make use of this feature which requires tracking of the changed artists each animation tick.
I get between ~15FPS on my MacBook Pro for 2 enabled very noisy power meter signals.
* The default `axis.legend()` call is not compatible with blitted animations. So therefore I simply create my own small "legend" by using `axis.annotate()` calls.
* For debugging performance, I included an FPS counter in the live plot (disabled by default, can be enabled with global setting).
* setting x-axis and y-axis limits is very heavy on performance - so I check if its necessary (i.e. last limits within certain bounds of new limits) …
=> Use blitting in live plot to improve performance

LabExT/Experiments/AutosaveDict.py
This replaces the 4-spaces indentation in the stored json files with a "tab" saving roughly 30% of the original file size without compromising readability.
=> json tab indentation

LabExT/Tests/View/Controls/DriverPathDialog_test.py, LabExT/Tests/View/Controls/Wizard_test.py, LabExT/Tests/View/CoordinatePairingsWindow_test.py, LabExT/Tests/View/ExperimentWizard_test.py, LabExT/Tests/View/MainWindow_test.py, requirements_testing.txt, tox.ini
Flaky is a test plugin that we used to re-run a failed test up to three times. This was necessary as our GUI integration tests sometimes did not have Tk not properly initiated.
However, [Flaky seems to be an abandoned project](https://github.com/box/flaky/issues/192).  Furthermore, all Python 3.10 tests started to fail on 4th March 2024 due to an import error within the Flaky module.
This PR replaces flaky with the pytest internal [pytest-rerunfailures](https://github.com/pytest-dev/pytest-rerunfailures). This should keep us future-proof in our testing.
=> Replacing flaky with pytes-rerunfailures

AUTHORS.md, LabExT/Instruments/PowerMeterSimulator.py, LabExT/Logs/LoggingWidgetHandler.py, LabExT/View/LiveViewer/Cards/PowerMeterCard.py, LabExT/View/LiveViewer/LiveViewerModel.py
Due to our fancy log widget in the MainWindow of LabExT, every logging action actually triggered a redraw of the Tk windows. This is not a thread safe action and caused crashes when the live-viewer thread was emitting log messages.
This PR implements a hotfix such that the optical power meter does not crash the live viewer anymore on a wrong range setting and is not intended as a long-term solution.
As a long-term fix, I'd suggest not using any logging in the instrument drivers, but simply throw errors and let code higher up in the hierarchy handle the issues. - Let's discuss soon.
(also, adding Dillon to authors list)
=> hotfix: logging within live viewer crashes GUI

LabExT/View/MainWindow/MainWindowController.py, LabExT/View/MainWindow/MainWindowView.py, LabExT/View/MenuListener.py
Make LabExT more user friendly by saving entered chip params more often than just on graceful exit. Sometimes, LabExT crashes (gasp!), and then the chip parameters need to be re-entered, because they weren't saved because there was no graceful exit!
Any button that is in the main window now also calls saving of the chip parameters to disk. As the chance of pressing any of the buttons is very high once the chip settings were adapted, this serves as a good proxy to "save immediately". This also works when using the keyboard shortcuts!
No compatibility issues expected.
=> Save chip info in MainWindow more often than just on exit

LabExT/View/AddonSettingsDialog.py, LabExT/View/Controls/CustomTable.py
In the Addon Settings menu, LabExT would crash if you clicked on the header of any of the tables.
For example,  if you were to click on the "Imported From"  header:
```
+--------------------+--------------------------------------------+
| Measurement Class  |               Imported From                |
+--------------------+--------------------------------------------+
| DummyMeas          |                                            | <- resolved to float("+inf")
| ->                 | /home/.../LabExT/.../DummyMeas.py          | <- resolved to string
| InsertionLossSweep |                                            |
| ->                 | /home/.../LabExT/.../InsertionLossSweep.py |
+--------------------+--------------------------------------------+
```
And python would try to compare …
=> Fix bug causing LabExT to crash when trying to sort table

LabExT/View/LiveViewer/LiveViewerController.py
I was not deep-copying the lists that keep the values of the live plots. This lead to the behavior of re-saving the live-viewer data every time somebody changed metadata of the snapshots.
This is a critical bugfix that needs to be merged to main ASAP.
=> Critical bugfix: live viewer snapshots did not save data at time of clicking, but continuously saved incoming data!

LabExT/View/Controls/ParameterTable.py, LabExT/View/LiveViewer/LiveViewerController.py
=> Bugfix: LV snapshots failed to save if a card did not have parameters associated

LabExT/Measurements/MeasAPI/Measparam.py, LabExT/View/Controls/SweepParameterFrame.py, LabExT/View/EditMeasurementWizard/WizardEntry/SaveButtons.py
Just adding the option to setup a sweep through all entries in a `MeasParamList` parameter of a measurement.
Also, fixed two bugs:
* `MeasParamInt` was not able to be swept as it tried to assign a float value to an int param
* There was an off-by-one error setting up the sweep of type `step_size`.
=> Sweeps now also handles lists -> unconditionally cycle through all list entries.

LabExT/View/AddonSettingsDialog.py, LabExT/View/Controls/CustomTable.py
The current dialog for managing addons was difficult to read and extend. This PR refreshes the UI of the addon settings dialog, while maintaing its core structure and functionality.
This PR should be merged before #215 (Export Addons)
The textbox that held all the addon search paths has been replaced by a list of current addon paths as well as a single text input and a 'browse' button to allow users to select a path from their own filesystem. This UI attempts to remove possible error from leaving a wrong character or accidental newline in the old textbox.
The ability to copy/paste the entire list of addon search paths has been lost.
The old tables have been replaced by a tab view, which makes navigating currently loaded extentions much easier. Each tab contains a treeview with the …
=> Addon Settings Dialog UI update
