.github/workflows/labext-ci.yml
Adding opening a Pull Request as trigger for CI.
=> Trigger CI on Pull Request

README.md, docs/installation.md, docs/setup_dev_env.md, mkdocs.yml
Extend README for instructions for testing LabExT.
=> README: Add testing instructions

LabExT/Measurements/DummyMeas.py
See title: small bugfix in dummy meas
=> DummyMeas.py: now sleeps in any case

requirements.txt
Updated and tested dependencies in requirements.txt. Everything fine.
=> Updated requirements to newest versions

docs/setup_dev_env.md
Update Documentation to give instructions how to run the test suite for lab and normal tests according to #36 .
=> [Documentation] Instructions for Testsuite

LabExT/Movement/Calibration.py, LabExT/Tests/Movement/Calibration_test.py
Adds a special movement method to wiggle a axis of a stage in order to verify the axes rotation.
=> Movement Calibration [7/7] Axis wiggling

LabExT/Movement/MoverNew.py, LabExT/Tests/Movement/MoverNew_test.py, LabExT/View/Movement/MovementWizard.py
Adds a z-Lift value to the mover, which can be configured in the MoverWizard.
Adds a method to safely raise and lower the stage.
=> Movement Mover: Z-Lift

LabExT/Movement/Calibration.py, LabExT/Movement/MoverNew.py, LabExT/Tests/Movement/MoverNew_test.py, LabExT/View/MainWindow/MainWindowView.py, LabExT/View/MenuListener.py, LabExT/View/Movement/MovementWizard.py
Adds a wizard to calibrate stages, i.e. define the axis rotation and define the coordinate pairings.
No new logic was added, only existing logic was simplified and moved.
GUI tests will follow.
=> Movement GUI [4/4] Calibration Wizard

LabExT/Movement/Calibration.py, LabExT/Movement/MoverNew.py, LabExT/Tests/Movement/MoverNew_test.py, LabExT/View/MainWindow/MainWindowView.py, LabExT/View/MenuListener.py, LabExT/View/Movement/MovementWizard.py
Adds a wizard with which stage drivers can be loaded and stages can be connected.
No new logic was added, only existing logic was simplified and moved.
GUI tests will follow.
=> Movement GUI [2/4] Stage Setup Wizard

LabExT/Movement/MoverNew.py, LabExT/Movement/Stage.py, LabExT/Movement/Stages/DummyStage.py, LabExT/Movement/Stages/Stage3DSmarAct.py, LabExT/View/Movement/CoordinatePairingsWindow.py, LabExT/View/Movement/MovementWizard.py
Absolute movement for multiple stages with collision free path planning.
=> [Movement]: Move absolute with Path Planning 

LabExT/Movement/MoverNew.py, LabExT/Movement/PathPlanning.py, LabExT/Movement/Stage.py, LabExT/Movement/Stages/DummyStage.py, LabExT/Movement/Stages/Stage3DSmarAct.py, LabExT/View/Movement/CoordinatePairingsWindow.py, LabExT/View/Movement/MovementWizard.py
Adds the implemtation for the path planning algorithm.
=> [Movement] Collision: Path Planning Algorithm

LabExT/Movement/MoverNew.py, LabExT/Movement/PathPlanning.py, LabExT/Movement/Stage.py, LabExT/Movement/Stages/DummyStage.py, LabExT/Movement/Stages/Stage3DSmarAct.py, LabExT/View/Movement/CoordinatePairingsWindow.py, LabExT/View/Movement/MovementWizard.py
Adds the implementation for the potential field algorithm.
The PotentialField class is created for each calibration that is to be moved to a target. The other calibrations are added as obstacles.
=> [Movement] Collision: Potential Field

LabExT/Movement/Calibration.py, LabExT/Movement/MoverNew.py, LabExT/Movement/Transformations.py, LabExT/Tests/Movement/Calibration_test.py, LabExT/Tests/Movement/Transformations_test.py, LabExT/View/MainWindow/MainWindowView.py, LabExT/View/MenuListener.py, LabExT/View/Movement/MoveStagesDeviceWindow.py, LabExT/View/Movement/MoveStagesRelativeWindow.py, LabExT/View/Movement/__init__.py
Redesign of the existing move relative of stages by GUI:
=> [Movement] Move relative with GUI

LabExT/Movement/Calibration.py, LabExT/Movement/MoverNew.py, LabExT/Movement/Transformations.py, LabExT/Movement/config.py, LabExT/Tests/Movement/Calibration_test.py, LabExT/Tests/Movement/MoverNew_test.py, LabExT/Tests/Movement/Transformations_test.py, LabExT/View/MainWindow/MainWindowView.py, LabExT/View/MenuListener.py, LabExT/View/Movement/MoveStagesDeviceWindow.py, LabExT/View/Movement/MoveStagesRelativeWindow.py, LabExT/View/Movement/MovementWizard.py, LabExT/View/Movement/__init__.py
Solves #87 
Adds a new implementation of the Kabsch Algorithm with orientation preservation.
Added test for all possible axes rotations.
=> [Movement] Update kabsch with orientation perservation

LabExT/Movement/MoverNew.py, LabExT/Movement/PathPlanning.py
Adds a check if target and start coordinates are approximately on the same z plane.
=> [Movement v1] Path Planning z level check

LabExT/View/Movement/MovementWizard.py
Saved pairings are now selectable in the table. The selected pairings can be deleted by a new button. To do this, all transformations are first reset and then recalculated with all points except those that have been selected.
=> [Movement v2] Delete coordinate pairings

LabExT/Movement/MoverNew.py, LabExT/View/MainWindow/MainWindowView.py
Disables options in Context Menu for Movement if they are not available in the current state.
=> Disable context menu options if not available

LabExT/Movement/PathPlanning.py, LabExT/Tests/Movement/PathPlanning_test.py
This PR changes the behaviour of polygons. These now allow to be (optionally) configurable. This PR does the groundwork for later PRs to optionally adjust these parameters in the GUI.
In the design of these parameters I have followed the design of the parameters for measurements.
=> Allow configuration for polygons

LabExT/View/MainWindow/MainWindowModel.py
Show better explanation if automatic movement is not available. Especially  "stage driver not loaded" was misleading.
=> Fix: Better explanation if automatic movement is not available

LabExT/View/MainWindow/MainWindowView.py
Add restart menu option in context menu.
=> Add restart menu option

LabExT/Movement/Stages/Stage3DSmarAct.py, LabExT/View/Controls/DriverPathDialog.py
Small fix: Handle the case if the stage driver file is missing.
=> Fix: Handle missing stage driver files

LabExT/Movement/PathPlanning.py, LabExT/View/Movement/MovementWizard.py
Allows the polygons to be configured during stage setup
=> Configure polygons during setup

LabExT/ExperimentManager.py, LabExT/Movement/MoverNew.py, LabExT/Movement/Stage.py, LabExT/Tests/Movement/MoverNew_test.py, LabExT/Tests/Utils.py, LabExT/Tests/View/CoordinatePairingsWindow_test.py, LabExT/View/AddonSettingsDialog.py, LabExT/View/Movement/MovementWizard.py
This PR allows the loading of stage classes from an arbitrary path from the disk, similar to Instruments and Measurements.
=> Addon support for stages

LabExT/Movement/Calibration.py, LabExT/Movement/Stage.py, LabExT/Movement/Stages/Stage3DSmarAct.py, LabExT/Tests/Movement/Calibration_test.py, LabExT/Tests/View/StageRegistrationWindow_test.py, LabExT/View/Controls/StageTable.py, LabExT/View/Movement/MovementWizard.py, LabExT/View/Movement/StageRegistrationWindow.py
This PR uses the wizard for new stages introduced in #162 . 
This makes the wizard much easier to use.
=> (6/8) Update Movement Wizard to use new Stage Registration Wizard

LabExT/Movement/Calibration.py, LabExT/Movement/Stage.py, LabExT/Movement/Stages/Stage3DSmarAct.py, LabExT/Tests/Movement/Calibration_test.py, LabExT/Tests/View/StageRegistrationWindow_test.py, LabExT/View/Controls/StageTable.py, LabExT/View/Movement/MovementWizard.py, LabExT/View/Movement/StageRegistrationWindow.py
Wizard window for editing and registering new calibration and integration tests.
=> (5/8) Add window to add and edit stages

LabExT/Movement/Calibration.py, LabExT/Movement/Stage.py, LabExT/Movement/Stages/Stage3DSmarAct.py, LabExT/Tests/Movement/Calibration_test.py, LabExT/Tests/View/StageRegistrationWindow_test.py, LabExT/View/Controls/StageTable.py, LabExT/View/Movement/MovementWizard.py, LabExT/View/Movement/StageRegistrationWindow.py
A table for the selection of stages available on the PC.
=> (4/8) Add stage table to select available stages

LabExT/Logs/CustomLogFormatter.py, LabExT/Logs/LoggingWidgetHandler.py
The output in the loggin window (and in the terminal) is now colored.
=> Colored logging output

LabExT/SearchForPeak/PeakSearcher.py, LabExT/View/Controls/InstrumentSelector.py, LabExT/View/SearchForPeakPlotsWindow.py
- This adds a "Save Parameter" button to the search-for-peak window to independently save the parameters without executing the SfP action
- bugfix: loading sfp parameter save file
- bugfix: serializing sfp instrument save file
=> SfP bugfix and save button

LabExT/Experiments/StandardExperiment.py, LabExT/Experiments/TypeHints.py, LabExT/Measurements/DummyMeas.py, LabExT/ViewModel/Utilities/ObservableList.py
This PR is just some basic housekeeping.
There are now new types for the measurement dictionaries, some files have been correctly reformatted using Black and the `ObservableList` has generic types (In a pre 3.11 way).
**No logic was changed in these commits!**
=> General Type Hinting and Import Fixing

LabExT/View/MeasurementTable.py
This PR supercedes #198 after rebasing to the base branch.
The changes were reviewed and approved in #198
=> Feature/advanced plotting/measurement table [2/6] Rebase 01

LabExT/Experiments/StandardExperiment.py, LabExT/Experiments/TypeHints.py, LabExT/Measurements/MeasAPI/Measparam.py, LabExT/View/Controls/Plotting/PlotController.py, LabExT/View/Controls/Plotting/PlottableDataHandler.py, LabExT/View/MainWindow/MainWindowView.py, LabExT/View/MeasurementTable.py
The changes were reviewed and accepted there. It was now rebased onto the base branch.
=> Feature/advanced plotting/plottable data handler [3/6] Rebased

LabExT/View/Controls/Plotting/PlotConstants.py, LabExT/View/Controls/Plotting/PlotController.py, LabExT/View/Controls/Plotting/PlotModel.py, LabExT/View/Controls/Plotting/PlotView.py
The changes were approved there.
=> Feature/advanced plotting/line plotting [4/6] Rebased

LabExT/Experiments/StandardExperiment.py, LabExT/View/Controls/Plotting/PlotConstants.py, LabExT/View/Controls/Plotting/PlotController.py, LabExT/View/Controls/Plotting/PlotModel.py, LabExT/View/Controls/Plotting/PlotView.py
=> Feature/advanced plotting/contour plotting [5/6] Rebased

LabExT/View/Controls/Plotting/PlotController.py, LabExT/View/Controls/Plotting/PlotModel.py, LabExT/View/Controls/Plotting/PlotView.py
=> Feature/advanced plotting/legend [6/6] Rebased
